{% set name = "tracktable-data" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sandialabs/tracktable-data/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6d3c559cb99785d4623cc39701dde56f083d09d3631840c601726bef83b74f0f
build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m build . -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - build
    - setuptools
  run:
    - python >=3.5

test:
  imports:
    - tracktable_data
    - tracktable_data.data
    - tracktable_data.python_info_data
    - tracktable_data.python_example_data
    - tracktable_data.internal_test_data
  commands:
    - python -c "from tracktable_data.data import retrieve; files = retrieve(); assert len(files) > 0"
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://tracktable.sandia.gov/
  license_file: LICENSE.txt
  license: BSD-2-Clause
  license_url: https://opensource.org/licenses/BSD-2-Clause
  license_family: BSD
  summary: 'Trajectory Analysis and Rendering'
  description: >
    Tracktable-Data is a supplimental data package for the Tracktable library.
    Refer to the Tracktable documentation and Github repository for more
    information on Tracktable's capabilities and usage.
  dev_url: https://github.com/sandialabs/tracktable-data
  doc_url: https://tracktable.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pabaxley
    - atwilso
